name: Daily Reto

on:
  schedule:
    - cron: "0 0 * * *" # todos los días a medianoche UTC
  workflow_dispatch:

permissions:
  contents: write # 👈 necesario para que el bot pueda hacer push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Debug files
        run: ls -la

      - name: Generate daily reto
        run: node scripts/generate-daily-reto.js

      - name: Commit and push changes
        run: |
          git config --local user.email "mathgym-bot@github.com"
          git config --local user.name "MathGym Bot"
          git add .

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          FECHA="$(date +%Y-%m-%d)"
          git commit -m "🎲 Daily reto generated for $FECHA"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mathgymdcr/mathgym.git HEAD:main
